## https://docs.google.com/spreadsheets/d/1eJm9BLSt45iH4WW8ck1Wul9bfCG3bla9G1A4-cLSxug/edit#gid=172145375

User:
  userId: String

    Battle:
      userId: String
      matchId: String
      partyId: String?
      opponentParty: List<String>
      divisorList6: List<String>
      divisorList5: List<String>
      divisorList4: List<String>
      divisorList3: List<String>
      divisorList2: List<String>
      divisorList1: List<String>
      opponentOrder: List<int>
      myOrder: List<int>
      memo: String
      eachMemo: Map<String,String>
      result: String
      createdAt: Timestamp

    Party:
      userId: String
      partyId: String
      name: String
      partyNameList: List<String>
      divisorList6: List<String>
      divisorList5: List<String>
      divisorList4: List<String>
      divisorList3: List<String>
      divisorList2: List<String>
      divisorList1: List<String>
      memo: String
      eachMemo: Map<String,String>
      createdAt: Timestamp

