## https://docs.google.com/spreadsheets/d/1eJm9BLSt45iH4WW8ck1Wul9bfCG3bla9G1A4-cLSxug/edit#gid=172145375

User:
  userId: String
  userName: String

    Battle:
      userId: String
      partyId: String?
      opponentParty: List<String>
      divisorList: List<String>
      order: List<String>
      memo: String
      eachMemo: Map<String,String>
      result: String
      createdAt: TimeStamp

    Party:
      userId: String
      partyId: String
      party: List<String>
      divisorList: List<String>
      eachMemo: Map<String,String>

